- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom # Corvax-JobSupervisors
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterVestWeb
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: RubberStampCentcom
    pocket2: ClothingMaskGasCentcom
    underwearb: ClothingUnderwearBottomBoxersCentcomm # Sirena-Underwear
  underweart: ClothingUnderwearTopBraCentcomm # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesCentcomm # Sirena-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtPencilCentcomOfficial
