- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 288000 # 80 hours
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  extendedAccess:
  - Paramedic
  - Coroner
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    underwearb: ClothingUnderwearBottomBoxersSeniorPhysician # DS14-Underwear
  underweart: ClothingUnderwearTopBraSeniorPhysician # DS14-Underwear
  underwearb: ClothingUnderwearBottomPantiesSeniorPhysician # DS14-Underwear
  storage:
    back:
    - BoxSurvivalMedical
