- type: startingGear
  id: CentcomOfficerCommand
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficer
    back: ClothingBackpackERTMedicalFilled
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasAtmosian
    outerClothing: ClothingOuterArmorHeavyGreen
    eyes: ClothingEyesGlassesSecurity
    id: CentcomPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetCentCom
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
