- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Fland
  - Meta
  - Packed
  - Cluster
  # - Oasis # Ожидает ремаппа под билд
  - Omega
  - Bagel
  - Origin
  - Box
  - Core
  - Marathon
  - Aspid
  - Barratry
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxGate
  - CorvaxGelta
  - CorvaxSilly
  - CorvaxPaper
  - CorvaxAstra
  # - CorvaxIshimura # Ожидает ремаппа под билд
  - CorvaxSpectrum
  - Gemini
  - Train
