- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    id: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
    pocket1: CluwneHorn
    underwearb: ClothingUnderwearBottomBoxersClown # Sirena-Underwear
  underweart: ClothingUnderwearTopBraClown # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesClown # Sirena-Underwear

- type: startingGear
  id: HoloClownGear
  equipment:
    pocket1: BikeHorn

