- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  requirements:
    - !type:OverallPlaytimeRequirement
        time: 3600 # 1 hour
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Cargo
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: CargoTechGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    underwearb: ClothingUnderwearBottomBoxersCargoTechnician # DS14-Underwear
  underweart: ClothingUnderwearTopBraCargoTechnician # DS14-Underwear
  underwearb: ClothingUnderwearBottomPantiesCargoTechnician # DS14-Underwear
  storage:
    back:
    - BoxSurvival
