- type: entity
  save: false
  parent:
  - MobBloodstream
  - BaseMobSpecies
  - MobFlammable
  id: BaseMobSpeciesXenoSponsor
  abstract: true
  components:
  - type: EmotePanel
  - type: Flashable
  # Organs
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
    - Stutter
    - SeeingRainbows
    - Electrocution
    - ForcedSleep
    - TemporaryBlindness
    - Drunk
    - SlurredSpeech
    - RatvarianLanguage
    - PressureImmunity
    - Muted
    - Pacified
    - StaminaModifier
  - type: Blindable
  - type: Temperature
    heatDamageThreshold: 5000
    currentTemperature: 310.15
    specificHeat: 42
    heatDamage:
      types:
        Heat : 1 #per second, scales with temperature & other constants
  - type: Barotrauma
    damage:
      types:
        Blunt: 0.5 #per second, scales with pressure and other constants.
  - type: Hunger
  - type: Thirst
  - type: MobPrice
    price: 3000 # Kidnapping a living person and selling them for cred is a good move.
    deathPenalty: 0.1 # However they really ought to be living and intact, otherwise they're worth 100x less.
  - type: TypingIndicator
    proto: alien
  - type: Speech
    speechVerb: LargeMob
    speechSounds: Lizard
  - type: EmoteOnDamage
    withChat: true
    hiddenFromChatWindow: false
    emotes:
    - ScreamOnDamage
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: Xeno
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: InteractionOutline
  - type: Bloodstream
    bloodReagent: FluorosulfuricAcid
    bloodlossDamage:
      types:
        Bloodloss:
          1
    bloodlossHealDamage:
      types:
        Bloodloss:
          -1
    maxBleedAmount: 0
    chemicalMaxVolume: 0
  - type: DrawableSolution
    solution: bloodstream
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 150
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: HealthExaminable
    examinableTypes:
      - Blunt
      - Slash
      - Piercing
      - Heat
      - Shock
    locPrefix: silicon
  - type: Actions
  - type: Vocal
    sounds:
      Male: UnisexXeno
      Female: UnisexXeno
      Unsexed: UnisexXeno
  - type: MeleeWeapon
    soundHit:
     collection: AlienClaw
    animation: WeaponArcClaw
    damage:
      types:
        Slash: 6
  - type: MovementSpeedModifier
    baseWalkSpeed: 2.6
    baseSprintSpeed: 4.6
  - type: InteractionPopup
    successChance: 1.0
    interactSuccessString: petting-success-bingus
    interactFailureString: petting-failure-generic
    interactSuccessSpawn: EffectHearts
    interactSuccessSound:
      path: /Audio/DeadSpace/Sponsor/Sound/meow_xeno.ogg
  - type: Butcherable
    butcheringType: Spike
    spawned:
      - id: FoodMeatXeno
        amount: 5

- type: damageModifierSet
  id: Xeno
  coefficients:
    Blunt: 0.8
    Slash: 0.8
    Piercing: 1
    Shock: 1.2
    Cold: 0.8
    Heat: 1.5
    Poison: 0
    Radiation: 1
    Caustic: 0.5
