- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-magistrat-iaa
  canBeAntag: false
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLaw
    underwearb: ClothingUnderwearBottomBoxersLawyer # DS14-Underwear
  underweart: ClothingUnderwearTopBraLawyer # DS14-Underwear
  underwearb: ClothingUnderwearBottomPantiesLawyer # DS14-Underwear
  inhand:
    - BriefcaseLawyerFilled
  storage:
    back:
    - BoxSurvival
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - HyperLinkBookSOPLaw
