- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 54000 # 15 hours
      inverted: true # stop playing intern if you're good at science!
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  access:
  - Research
  - Maintenance
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Science
  wage: 25
  #end-backmen: currency

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    underwearb: ClothingUnderwearBottomBoxersResearchAssistant # DS14-Underwear
  underweart: ClothingUnderwearTopBraResearchAssistant # DS14-Underwear
  underwearb: ClothingUnderwearBottomPantiesResearchAssistant # DS14-Underwear
  storage:
    back:
    - BoxSurvival
