- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 144000 # 40 hours
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 108000 # 30 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hours
