- type: job
  id: TypanBotanist
  name: Ботаник Синдиката
  playTimeTracker: TypanBotanist
  description: Ботаник из далёкого космоса
  startingGear: SyndicateBotanist
  icon: "JobIconTypanBotanist"
  supervisors: job-supervisors-hop

- type: startingGear
  id: SyndicateBotanist
  equipment:
    ears: ClothingHeadsetAltSyndicate
    jumpsuit: ClothingUniformJumpsuitTypanBotanist
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesColorBlack
    id: TypanIDCardBotanist
