- type: job
  id: TypanChef
  name: Повар Синдиката
  playTimeTracker: TypanChef
  description: Повар из далёкого космоса
  startingGear: SyndicateChef
  icon: "JobIconTypanChef"
  supervisors: job-supervisors-hop

- type: startingGear
  id: SyndicateChef
  equipment:
    ears: ClothingHeadsetAltSyndicate
    jumpsuit: ClothingUniformJumpsuitTypanChef
    back: ClothingBackpackSyndicate
    outerClothing: ClothingOuterApronTypanChef
    shoes: ClothingShoesColorBlack
    id: TypanIDCardChef
